apiVersion: v1
kind: Service
metadata:
  name: myapp-stable # Đúng tên đã khai báo trong rollout
  namespace: phase6-task5
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: myapp # Phải trùng với selector của Rollout
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-canary # Đúng tên đã khai báo trong rollout
  namespace: phase6-task5
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: myapp # Phải trùng với selector của Rollout